import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactNode,
} from "react";
import type {
  AfterActivation,
  GroupExit,
  ScannerOptions,
  SelectionDelayOptions,
  StartOn,
} from "../../core/types.ts";
import { normalizeSwitch } from "../../core/input/switches.ts";
import type {
  DiscreteAction,
  SwitchAction,
  SwitchDefinition,
} from "../../core/input/switches.ts";
import { isDevelopment } from "../../core/shared/env.ts";
import { warnDev } from "../devWarnings.ts";
import type { ScanMethod } from "../../core/methods/methods.ts";
import { ScannerProvider } from "../ScannerProvider.tsx";
import {
  useKeyboardSwitches,
  type KeyboardSwitchBindings,
  type UseKeyboardSwitchesOptions,
} from "../hooks/useKeyboardSwitches.ts";
import { useOwnedScanner } from "../hooks/useOwnedScanner.ts";

export type { DiscreteAction, SwitchAction, SwitchDefinition };

/** Less-common traversal behavior, kept off the primary component props. */
export interface SwitchScannerBehavior {
  afterActivation?: AfterActivation;
  groupExit?: GroupExit;
  selectionDelay?: SelectionDelayOptions;
}

/** A full gesture definition with an optional shared logical identity. */
export type SwitchGesture = SwitchDefinition & { readonly id?: string };

/** A gesture bound to a key. Alias of {@link SwitchGesture}. */
export type KeyboardGesture = SwitchGesture;

/** A key can name an action directly or describe a stabilized gesture. */
export type KeyboardBinding = SwitchAction | SwitchGesture;

/** Map from `KeyboardEvent.code` directly to scanner intent. */
export type KeyboardActionBindings = Readonly<Record<string, KeyboardBinding>>;

/** Keyboard ownership options accepted by {@link SwitchScanner}. */
export type SwitchScannerKeyboardOptions = Omit<
  UseKeyboardSwitchesOptions,
  "enabled"
>;

/** Props for the application-level scanner boundary. */
export interface SwitchScannerProps {
  method: ScanMethod;
  keyboard?: KeyboardActionBindings;
  /** When scanning begins. Defaults to `"input"`: the first accepted input. */
  start?: StartOn;
  enabled?: boolean;
  behavior?: SwitchScannerBehavior;
  keyboardOptions?: SwitchScannerKeyboardOptions;
  children?: ReactNode;
}

interface CompiledInput {
  readonly switches: Readonly<Record<string, SwitchDefinition>>;
  readonly keyboard: KeyboardSwitchBindings;
  readonly hasKeyboardBindings: boolean;
  readonly hasBackBinding: boolean;
  readonly hasScanBinding: boolean;
}

/**
 * Logical IDs generated by this surface. User-supplied IDs may not enter these
 * namespaces; plain actions and generated keys already own them.
 */
const RESERVED_ID_PREFIXES = ["action:", "key:", "switch:"] as const;

/** @internal Stable logical ID used by declarative action controls. */
function actionSwitchId(action: SwitchAction): string {
  return `action:${action}`;
}

function actionDefinition(action: SwitchAction): SwitchDefinition {
  // Both arms build `{ action }`; the branch only narrows the union type.
  return action === "scan" ? { action } : { action };
}

/**
 * Canonical structural signature. Core normalization resolves defaults and
 * fixes key order, so semantically equal definitions compare equal no matter
 * how their properties were spelled. Invalid definitions throw core's own
 * validation errors here, at the surface that received them.
 */
function definitionSignature(id: string, definition: SwitchDefinition): string {
  return JSON.stringify(normalizeSwitch(id, definition));
}

function assertUserSwitchId(id: string, source: string): void {
  for (const prefix of RESERVED_ID_PREFIXES) {
    if (id.startsWith(prefix)) {
      throw new TypeError(
        `[switch-scanning] ${source} id "${id}" uses the reserved "${prefix}" namespace; pick another id, or name the action directly to share its built-in control`,
      );
    }
  }
}

function bindsAction(
  definition: SwitchDefinition,
  action: SwitchAction,
): boolean {
  if ("tap" in definition) {
    return definition.tap === action || definition.hold.action === action;
  }
  return definition.action === action;
}

interface DeclaredControl {
  readonly definition: SwitchDefinition;
  readonly signature: string;
  readonly count: number;
}

type DeclaredControls = ReadonlyMap<string, DeclaredControl>;

/** @internal Register one on-screen control's logical switch for its lifetime. */
type DeclareSwitchControl = (
  id: string,
  definition: SwitchDefinition,
  signature: string,
) => () => void;

const SwitchScannerContext = createContext<DeclareSwitchControl | null>(null);

/** @internal Resolve the declarative boundary's control registrar or fail loudly. */
export function useDeclareSwitchControl(
  hookName: string,
): DeclareSwitchControl {
  const declare = useContext(SwitchScannerContext);
  if (!declare) {
    throw new Error(
      `[switch-scanning] ${hookName} must be used inside <SwitchScanner>. Under an advanced <ScannerProvider>, use usePointerSwitch from "@shayc/switch-scanning/react/advanced" instead.`,
    );
  }
  return declare;
}

/** @internal Compile the small React input surface into the existing engine model. */
export function compileSwitchScannerInput(
  keyboard: KeyboardActionBindings | undefined,
  controls?: DeclaredControls,
): CompiledInput {
  const switches: Record<string, SwitchDefinition> = {};
  const signatures: Record<string, string> = {};
  const bindings: Record<string, string> = {};

  const register = (
    id: string,
    definition: SwitchDefinition,
    signature: string,
  ): void => {
    const existing = signatures[id];
    if (existing !== undefined && existing !== signature) {
      throw new TypeError(
        `[switch-scanning] declarative control "${id}" has conflicting gesture definitions`,
      );
    }
    switches[id] = definition;
    signatures[id] = signature;
  };

  for (const [code, binding] of Object.entries(keyboard ?? {})) {
    if (typeof binding === "string") {
      const id = actionSwitchId(binding);
      const definition = actionDefinition(binding);
      register(id, definition, definitionSignature(id, definition));
      bindings[code] = id;
      continue;
    }

    const { id: explicitId, ...rawDefinition } = binding;
    if (explicitId !== undefined) assertUserSwitchId(explicitId, "keyboard");
    const id = explicitId ?? `key:${code}`;
    const definition = rawDefinition;
    register(id, definition, definitionSignature(id, definition));
    bindings[code] = id;
  }

  for (const [id, control] of controls ?? []) {
    register(id, control.definition, control.signature);
  }

  const definitions = Object.values(switches);
  return {
    switches,
    keyboard: bindings,
    hasKeyboardBindings: Object.keys(bindings).length > 0,
    hasBackBinding: definitions.some((d) => bindsAction(d, "back")),
    hasScanBinding: definitions.some((d) => bindsAction(d, "scan")),
  };
}

/** @internal Shared by useSwitch to mirror keyboard-binding compilation. */
export function resolveSwitchBinding(
  binding: SwitchAction | SwitchGesture,
  generatedId: string,
  source: string,
): { switchId: string; definition: SwitchDefinition; signature: string } {
  if (typeof binding === "string") {
    const switchId = actionSwitchId(binding);
    const definition = actionDefinition(binding);
    return {
      switchId,
      definition,
      signature: definitionSignature(switchId, definition),
    };
  }
  const { id: explicitId, ...rawDefinition } = binding;
  if (explicitId !== undefined) assertUserSwitchId(explicitId, source);
  const switchId = explicitId ?? `switch:${generatedId}`;
  const definition = rawDefinition;
  return {
    switchId,
    definition,
    signature: definitionSignature(switchId, definition),
  };
}

function scannerOptions(
  props: {
    method: ScanMethod;
    start: StartOn | undefined;
    enabled: boolean | undefined;
    behavior: SwitchScannerBehavior | undefined;
  },
  compiled: CompiledInput,
): ScannerOptions {
  const options: ScannerOptions = {
    method: props.method,
    switches: compiled.switches,
    startOn: props.start ?? "input",
    enabled: props.enabled ?? true,
  };
  if (props.behavior?.afterActivation !== undefined) {
    options.afterActivation = props.behavior.afterActivation;
  }
  const groupExit = props.behavior?.groupExit;
  if (groupExit !== undefined) {
    // "back-only" without a back binding would trap the user inside groups.
    // Keep the default Exit item until a back control exists (a dev warning
    // below names the missing binding).
    if (groupExit !== "back-only" || compiled.hasBackBinding) {
      options.groupExit = groupExit;
    }
  }
  if (props.behavior?.selectionDelay !== undefined) {
    options.selectionDelay = props.behavior.selectionDelay;
  }
  return options;
}

const EMPTY_CONTROLS: DeclaredControls = new Map();

/**
 * Own a scanner, keyboard adapter, DOM host, and target registry from one
 * declarative boundary. The first accepted input starts scanning by default.
 */
export function SwitchScanner(props: SwitchScannerProps): ReactNode {
  const [controls, setControls] = useState<DeclaredControls>(EMPTY_CONTROLS);
  // Mirror of the latest controls, updated synchronously so declarations made
  // in the same effect phase see each other's conflicts exactly.
  const controlsRef = useRef(controls);

  const declareControl = useCallback<DeclareSwitchControl>(
    (id, definition, signature) => {
      const current = controlsRef.current;
      const existing = current.get(id);
      if (existing && existing.signature !== signature) {
        throw new TypeError(
          `[switch-scanning] declarative control "${id}" has conflicting gesture definitions`,
        );
      }
      const added = new Map(current);
      added.set(
        id,
        existing
          ? { ...existing, count: existing.count + 1 }
          : { definition, signature, count: 1 },
      );
      controlsRef.current = added;
      if (!existing) setControls(added);

      let released = false;
      return () => {
        if (released) return;
        released = true;
        const map = controlsRef.current;
        const entry = map.get(id);
        if (!entry) return;
        const removed = new Map(map);
        if (entry.count > 1) {
          removed.set(id, { ...entry, count: entry.count - 1 });
          controlsRef.current = removed;
          return;
        }
        removed.delete(id);
        controlsRef.current = removed;
        setControls(removed);
      };
    },
    [],
  );

  const { method, start, enabled: enabledProp, behavior, keyboard } = props;
  const compiled = useMemo(
    () => compileSwitchScannerInput(keyboard, controls),
    [keyboard, controls],
  );
  const options = useMemo(
    () =>
      scannerOptions(
        { method, start, enabled: enabledProp, behavior },
        compiled,
      ),
    [method, start, enabledProp, behavior, compiled],
  );
  const scanner = useOwnedScanner(options);

  const enabled = enabledProp ?? true;
  const keyboardOptions: UseKeyboardSwitchesOptions =
    compiled.hasKeyboardBindings
      ? { ...props.keyboardOptions, enabled }
      : { enabled: false, target: null };
  useKeyboardSwitches(scanner, compiled.keyboard, keyboardOptions);

  const groupExit = props.behavior?.groupExit;
  useEffect(() => {
    if (!isDevelopment()) return;
    if (groupExit !== "back-only" || compiled.hasBackBinding) return;
    // Defer past the current effect phase: on mount, descendant useSwitch
    // declarations land one commit later and cancel this warning.
    const timer = setTimeout(() => {
      warnDev(
        "back-only-unbound",
        'groupExit "back-only" has no control mapped to "back"; the default group Exit item stays available until one is bound',
      );
    }, 0);
    return () => clearTimeout(timer);
  }, [groupExit, compiled.hasBackBinding]);

  const methodKind = props.method.kind;
  useEffect(() => {
    if (!compiled.hasScanBinding) return;
    if (methodKind !== "step" && methodKind !== "dwell") return;
    warnDev(
      "scan-action-ignored",
      `the "scan" action has no effect under the "${methodKind}" method and can cancel a pending dwell; bind a discrete action instead`,
    );
  }, [methodKind, compiled.hasScanBinding]);

  return (
    <SwitchScannerContext.Provider value={declareControl}>
      <ScannerProvider scanner={scanner}>{props.children}</ScannerProvider>
    </SwitchScannerContext.Provider>
  );
}
